---
# tasks file for ansible-mysql

- name: Preseed
  debconf:
    name: mysql-server-5.5
    question: '{{ item }}'
    vtype: password
    value: '{{ mysql_root_password }}'
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: apt install
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mysql-server-5.5
    - mysql-client-5.5
    - python-mysqldb
    - cron

- name: Create database
  when: mysql_database is defined
  mysql_db:
    login_user: root
    login_password: '{{ mysql_root_password }}'
    collation: utf8_general_ci
    encoding: utf8
    name: '{{ mysql_database }}'
    state: present

- name: Create account
  when: mysql_user is defined and mysql_database is defined
  mysql_user:
    login_user: root
    login_password: '{{ mysql_root_password }}'
    name: '{{ mysql_user }}'
    password: '{{ mysql_password|default(omit) }}'
    priv: '{{ mysql_database }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,INDEX'
    state: present

- name: Add daily backup job
  copy:
    src: backup.sh
    dest: /etc/cron.daily/mysql
    owner: root
    group: root
    mode: '0755'
